// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type MasterStatus struct {
	ID     int32
	Status string
}

type Task struct {
	ID          int32
	Title       string
	Description sql.NullString
	StatusID    sql.NullInt32
	UserID      sql.NullInt32
	StartTime   sql.NullTime
	EndTime     sql.NullTime
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type User struct {
	ID        int32
	Name      string
	Email     string
	Password  string
	CreatedAt sql.NullTime
}
