// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const addUser = `-- name: AddUser :execresult
INSERT INTO users (name,email, password)
VALUES(?,?,?)
`

type AddUserParams struct {
	Name     string
	Email    string
	Password string
}

func (q *Queries) AddUser(ctx context.Context, arg AddUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, addUser, arg.Name, arg.Email, arg.Password)
}

const createTask = `-- name: CreateTask :execresult
INSERT INTO tasks (title, description, status_id, user_id, start_time, end_time)
VALUES(?,?,?,?,?,?)
`

type CreateTaskParams struct {
	Title       string
	Description sql.NullString
	StatusID    sql.NullInt32
	UserID      sql.NullInt32
	StartTime   sql.NullTime
	EndTime     sql.NullTime
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createTask,
		arg.Title,
		arg.Description,
		arg.StatusID,
		arg.UserID,
		arg.StartTime,
		arg.EndTime,
	)
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks WHERE id = ?
`

func (q *Queries) DeleteTask(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteTask, id)
	return err
}

const getTask = `-- name: GetTask :one
SELECT 
    t.id, 
    t.title, 
    t.description, 
    s.status AS status_name,
    t.user_id,
    t.start_time,
    t.end_time,
    t.created_at, 
    t.updated_at
FROM tasks t
JOIN master_status s ON t.status_id = s.id
WHERE t.id = ?
`

type GetTaskRow struct {
	ID          int32
	Title       string
	Description sql.NullString
	StatusName  string
	UserID      sql.NullInt32
	StartTime   sql.NullTime
	EndTime     sql.NullTime
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

func (q *Queries) GetTask(ctx context.Context, id int32) (GetTaskRow, error) {
	row := q.db.QueryRowContext(ctx, getTask, id)
	var i GetTaskRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.StatusName,
		&i.UserID,
		&i.StartTime,
		&i.EndTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, name, email, created_at
FROM users WHERE id = ?
`

type GetUserByIdRow struct {
	ID        int32
	Name      string
	Email     string
	CreatedAt sql.NullTime
}

func (q *Queries) GetUserById(ctx context.Context, id int32) (GetUserByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getUserById, id)
	var i GetUserByIdRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const listTasks = `-- name: ListTasks :many
SELECT 
    t.id, 
    t.title, 
    t.description, 
    s.status AS status_name,
    t.start_time,
    t.end_time,
    t.user_id,
    t.created_at, 
    t.updated_at
FROM tasks t
JOIN master_status s ON t.status_id = s.id
`

type ListTasksRow struct {
	ID          int32
	Title       string
	Description sql.NullString
	StatusName  string
	StartTime   sql.NullTime
	EndTime     sql.NullTime
	UserID      sql.NullInt32
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

func (q *Queries) ListTasks(ctx context.Context) ([]ListTasksRow, error) {
	rows, err := q.db.QueryContext(ctx, listTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTasksRow
	for rows.Next() {
		var i ListTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.StatusName,
			&i.StartTime,
			&i.EndTime,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTasks = `-- name: UpdateTasks :exec
UPDATE tasks
SET title = ?, description = ?, status_id = ?, start_time = ?, end_time = ?
WHERE id = ?
`

type UpdateTasksParams struct {
	Title       string
	Description sql.NullString
	StatusID    sql.NullInt32
	StartTime   sql.NullTime
	EndTime     sql.NullTime
	ID          int32
}

func (q *Queries) UpdateTasks(ctx context.Context, arg UpdateTasksParams) error {
	_, err := q.db.ExecContext(ctx, updateTasks,
		arg.Title,
		arg.Description,
		arg.StatusID,
		arg.StartTime,
		arg.EndTime,
		arg.ID,
	)
	return err
}
